### ISSUE TITLE
customization image

### ISSUE THREAD

**Issue by nooysters** [spree-contrib-variants/spree_product_customizations#7]
I'm trying to get the image upload to work

I permitted the  :customization_image attribute

``` ruby
Spree::PermittedAttributes.line_item_attributes << {
  product_customizations: [:customization_id, :option_id, :option_value, :customization_image ]
}
```

Modified the form

``` ruby
<%= field_set_tag product_customization_type.presentation do %>
  <% option = product_customization_type.customizable_product_options.first %>
  <div>
     <%= label(cust_dom_id.to_sym, option.presentation.to_sym) %>

    <% # create a slightly shorter dom_id field below.  I wish I could make use of dom_id for all strings that had [ && ] %>
    <%= hidden_field_tag "#{param_prefix}[customization_id]", product_customization_type.id %>
    <%= hidden_field_tag "#{param_prefix}[option_id]", product_customization_type.customizable_product_options.first.id %>
    <%= hidden_field_tag "#{param_prefix}[option_value]", product_customization_type.customizable_product_options.first.id %>
    <%= file_field_tag( "#{param_prefix}[customization_image]", class: "customization ", id: cust_dom_id ) %>

    <% # the price is stored here on change, and later collected by the product-wide updatePrice() %>
    <%= hidden_field_tag "customization_price", "0", :class => "customization_price" %>
    <%= link_to t("reset"),"" %>
  </div>
<% end # field_set_tag %>
```

Made it check for customization_image and set that to the option if it exists.

``` ruby
module Spree
  module ProductCustomizationsBuilder
    def build_product_customizations(options)
      return unless options

      customizations = {}

      options.each do |cust_opt_val|
        customization = customizations[cust_opt_val[:customization_id]] ||= {}
        #Allowing attribut option_value: :cusomization_image overrides option_value as a string so we assign it here. 
        if cust_opt_val.has_key? :customization_image
          customization[cust_opt_val[:option_id]] = {customization_image: cust_opt_val[:customization_image]}
        else        
          customization[cust_opt_val[:option_id]] = cust_opt_val[:option_value]
        end
      end

      customizations.each do |ct_id, cv_pair|
        # [customization_type_id =>
        #   { customized_product_option_id => <user input>, ... }]
        next if cv_pair.empty? || cv_pair.values.all?(&:empty?)

        # create a product_customization based on ct_id
        pc = product_customizations.build(product_customization_type_id: ct_id)
        puts cv_pair
        cv_pair.each_pair do |cust_opt_id, user_input|

        # create a customized_product_option based on cust_opt_id
          # and attach to its customization
          cpo = pc.customized_product_options.build(
            customizable_product_option_id: cust_opt_id
          )
          if user_input.is_a? String
            cpo.value = user_input
          else
            cpo.value = ""
            cpo.customization_image = user_input[:customization_image]
          end
        end
      end
    end
  end
end
```

when it hits
            cpo.customization_image = user_input[:customization_image]
the uploader loads but cpo.customization_image remains nil and the attribute is not added to the line item.

Any Ideas?

**Comment by sfcgeorge** [comment]
Firstly, this extension never worked, I tried to get the old version running but couldn't, so I have no idea how much of it was ever working. I've got most of it working now, but not the images.

This new extension uses new hooks in Spree to work rather than lots of monkeypatches, but they seem to be in an odd place. They're in Variant not LineItem and it's LineItems that get saved to an order not variants, so this extension can't actually save anything to the order! I don't know what the plan was to make saving work but it was never done. The way I made it work is by adding the built customization [back into the options hash](https://github.com/spree-contrib-variants/spree_product_customizations/blob/23b4ca7f8ff57d911835dad55e983e897b205bbd/app/models/spree/variant_decorator.rb#L45) which Spree then saves on the LineItem. I opened an [issue](https://github.com/spree/spree/issues/6610) on Spree asking if there's a better way, it's all a bit confusing.

Back to this issue. I'm not really sure. Where are images supposed to be saved? The field is on the [CustomizableProductOptions table](https://github.com/spree-contrib-variants/spree_product_customizations/blob/master/db/migrate/20140404214452_create_customizable_product_options.rb#L10) but the actual uploader appears to be in [CustomizedProductOption](https://github.com/spree-contrib-variants/spree_product_customizations/blob/master/app/models/spree/customized_product_option.rb#L8). So I don't know how it's meant to work, I guess you'll have to keep digging. It looks like you've made a good start though.

**Comment by nooysters** [comment]
Oh good I'm not the only one that found this confusing. I did add the customized_image column to CustomizedProductOption since carrier wave was expecting it there and was throwing an error. I will keep digging and be more liberal about rewriting things.
Thanks!

**Comment by sfcgeorge** [comment]
Ah. Alright, look at the [old extension](https://github.com/spree-contrib-variants/spree_flexi_variants) then as I assume it was working in that. It has so many monkeypatches, plus all the ad-hoc options stuff it might be hard to get your head around but hopefully will shed some light on what's meant to happen.

I was tempted to remove images as it seemed complicated, but if you need it I guess we'll keep it :)

**Comment by nooysters** [comment]
It looks like I got it working now, I submitted a pull request. I know you said I'm added as a contributor but I still can't merge pull requests or push to master.

**Comment by nooysters** [comment]
Nevermind :p I figured it out!
